#!/bin/bash
#Script Backup File System By Jose Miguel P.
#Script 2022

tar cvf "/tmp/backup/2022-$(date +"%m-%d-%Y")".tar /etc /var
gzip "/tmp/backup/2022-$(date +"%m-%d-%Y")".tar.gz
find . "/tmp/backup/2022-$(date +"%m-%d-%Y")".tar.gz -mtime -1 -type f -print &> /dev/null

if [ $? -eq 0 ]
	then
	echo "Backup Was Created Sucess"
	echo
	scp "/tmp/backup/2022-$(date +"%m-%d-%Y")".tar.gz user@192.168.10.23:/tmp/nas
	echo "Sent Backup to NAS"
	echo
	else
	echo "Backup Not Created - Failed"
fi
